language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

env:
  global:
    - TARGET=test

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: SYMFONY_VERSION=dev-master
    - php: 7.1
      env: SYMFONY_VERSION=4.1.*
    - php: 7.1
      env: SYMFONY_VERSION=4.0.*
    - php: 7.0
      env: TARGET=cs_dry_run
    - php: 5.5
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=3.4.*
  allow_failures:
    - php: hhvm
    - env: SYMFONY_VERSION=dev-master

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/twig-bundle:${SYMFONY_VERSION}" "symfony/framework-bundle:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/routing:${SYMFONY_VERSION}" "symfony/phpunit-bridge:${SYMFONY_VERSION}" --dev --no-update; fi;
  - if [ "$SYMFONY_VERSION" == "dev-master" ]; then sed -i "/minimum-stability/s/stable/dev/" composer.json; fi;
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
 - mkdir -p build/logs
 - make $TARGET

after_script:
 - php vendor/bin/coveralls -v

notifications:
 email: sk@xbug.de

